### ISSUE TITLE
inline-code font blurry

### ISSUE THREAD

**Issue by yunzhongxicao** [blueteafrog/logseq-mocha-theme#2]
Hi, when I try "< Src" to use inline-code, it seems  the font is blurry. As we can see from follow, the font has o border with another color;
![image](https://user-images.githubusercontent.com/52601843/167093657-26c0e90f-4052-4b95-9fde-53ade4ca5519.png)
![image](https://user-images.githubusercontent.com/52601843/167093924-e57824ca-ae70-40ae-8d48-ab54ed83db60.png)

**Comment by d5technews** [comment]
Hi sorry it took so long to respond. I'm not sure why I'm not receiving new issue notifications. Thank you for reporting I'll look into it asap.

**Comment by yunzhongxicao** [comment]
okk  thank you.   Expectation  for updating.

**Comment by d5technews** [comment]
Should be fixed. Please let me know if you experience any more issues
